export interface Plant {
  name: string;
  scientificName: string;
  type: "annual" | "perennial" | "shrub" | "vine" | "tree";
  usdaZones: string;
  bloomMonths: number[];
  color: string;
  colorHex: string;
  pollinatorScore: number;
  height: string;
  sunRequirement: "full-sun" | "part-shade" | "full-shade";
  waterNeeds: "low" | "medium" | "high";
  nativeRegions: string[];
  description: string;
  attractsSpecies: string[];
  tags: string[];
}

export const plants: Plant[] = [
  {
    name: "Trumpet Vine",
    scientificName: "Campsis radicans",
    type: "vine",
    usdaZones: "4–9",
    bloomMonths: [6, 7, 8, 9],
    color: "Orange-Red",
    colorHex: "#ff4500",
    pollinatorScore: 98,
    height: "30–40 ft",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Eastern North America"],
    description: "One of the top hummingbird plants. Produces masses of tubular orange-red flowers through summer. Very vigorous grower.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Black-chinned Hummingbird"],
    tags: ["native", "high-traffic", "summer-bloomer", "easy-care"],
  },
  {
    name: "Bee Balm",
    scientificName: "Monarda didyma",
    type: "perennial",
    usdaZones: "4–9",
    bloomMonths: [6, 7, 8],
    color: "Red / Pink",
    colorHex: "#e63946",
    pollinatorScore: 95,
    height: "2–4 ft",
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    nativeRegions: ["Eastern North America"],
    description: "Native wildflower with brilliant tubular flowers. Outstanding for ruby-throated hummingbirds. Also attracts bees and butterflies.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Broad-tailed Hummingbird"],
    tags: ["native", "summer-bloomer", "butterfly-friendly"],
  },
  {
    name: "Cardinal Flower",
    scientificName: "Lobelia cardinalis",
    type: "perennial",
    usdaZones: "3–9",
    bloomMonths: [7, 8, 9],
    color: "Scarlet Red",
    colorHex: "#c1121f",
    pollinatorScore: 99,
    height: "2–4 ft",
    sunRequirement: "part-shade",
    waterNeeds: "high",
    nativeRegions: ["North America"],
    description: "The premier native hummingbird plant. Its brilliant red tubular flowers are perfectly shaped for hummingbird bills. Thrives near water.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Rufous Hummingbird"],
    tags: ["native", "top-rated", "summer-bloomer", "shade-tolerant"],
  },
  {
    name: "Coral Honeysuckle",
    scientificName: "Lonicera sempervirens",
    type: "vine",
    usdaZones: "4–9",
    bloomMonths: [4, 5, 6, 7, 8, 9],
    color: "Coral-Red",
    colorHex: "#ff6f61",
    pollinatorScore: 92,
    height: "10–20 ft",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Eastern North America"],
    description: "Native vine with tubular red-orange flowers with yellow interiors. Long bloom period from spring through fall. Non-invasive unlike Japanese honeysuckle.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Black-chinned Hummingbird"],
    tags: ["native", "long-bloomer", "wildlife-value", "easy-care"],
  },
  {
    name: "Salvia (Red)",
    scientificName: "Salvia coccinea",
    type: "annual",
    usdaZones: "8–11 (annual elsewhere)",
    bloomMonths: [5, 6, 7, 8, 9, 10],
    color: "Red",
    colorHex: "#dc143c",
    pollinatorScore: 90,
    height: "1–3 ft",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Southeastern USA", "Tropical Americas"],
    description: "Easy-to-grow annual with spikes of bright red tubular flowers. Blooms continuously from spring until frost. Perfect for containers and borders.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Rufous Hummingbird", "Anna's Hummingbird"],
    tags: ["easy-care", "long-bloomer", "container-friendly", "drought-tolerant"],
  },
  {
    name: "Penstemon",
    scientificName: "Penstemon strictus",
    type: "perennial",
    usdaZones: "3–9",
    bloomMonths: [5, 6, 7],
    color: "Blue-Purple",
    colorHex: "#6a4c93",
    pollinatorScore: 88,
    height: "1–3 ft",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Western North America"],
    description: "Native perennial loved by western hummingbirds. Produces masses of tubular blue-purple flowers. Extremely drought-tolerant once established.",
    attractsSpecies: ["Black-chinned Hummingbird", "Broad-tailed Hummingbird", "Calliope Hummingbird"],
    tags: ["native", "drought-tolerant", "western-species", "low-maintenance"],
  },
  {
    name: "Columbine",
    scientificName: "Aquilegia canadensis",
    type: "perennial",
    usdaZones: "3–8",
    bloomMonths: [4, 5, 6],
    color: "Red-Yellow",
    colorHex: "#ff6b35",
    pollinatorScore: 87,
    height: "1–3 ft",
    sunRequirement: "part-shade",
    waterNeeds: "medium",
    nativeRegions: ["Eastern North America"],
    description: "Native woodland plant with distinctive spurred flowers designed for hummingbirds. Perfect for shaded garden spots. Self-seeds readily.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Broad-tailed Hummingbird"],
    tags: ["native", "spring-bloomer", "shade-tolerant", "self-seeding"],
  },
  {
    name: "Indian Paintbrush",
    scientificName: "Castilleja coccinea",
    type: "annual",
    usdaZones: "4–9",
    bloomMonths: [4, 5, 6, 7],
    color: "Scarlet",
    colorHex: "#ff2400",
    pollinatorScore: 94,
    height: "8–18 in",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Central and Western North America"],
    description: "Iconic wildflower of western meadows. The brilliant scarlet bracts attract hummingbirds from great distances. Partially parasitic on grass roots.",
    attractsSpecies: ["Rufous Hummingbird", "Broad-tailed Hummingbird", "Calliope Hummingbird"],
    tags: ["native", "wildflower", "western-species", "spring-bloomer"],
  },
  {
    name: "Fuchsia",
    scientificName: "Fuchsia magellanica",
    type: "shrub",
    usdaZones: "8–10",
    bloomMonths: [5, 6, 7, 8, 9, 10],
    color: "Pink-Purple",
    colorHex: "#c71585",
    pollinatorScore: 93,
    height: "2–8 ft",
    sunRequirement: "part-shade",
    waterNeeds: "medium",
    nativeRegions: ["South America"],
    description: "Classic hummingbird plant with pendant tubular flowers in pink and purple. Perfect for hanging baskets and borders in mild coastal climates.",
    attractsSpecies: ["Anna's Hummingbird", "Allen's Hummingbird", "Costa's Hummingbird"],
    tags: ["long-bloomer", "container-friendly", "coastal-garden", "shade-tolerant"],
  },
  {
    name: "Agave",
    scientificName: "Agave americana",
    type: "perennial",
    usdaZones: "8–11",
    bloomMonths: [5, 6, 7],
    color: "Yellow",
    colorHex: "#ffd700",
    pollinatorScore: 85,
    height: "20–30 ft (bloom spike)",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Southwestern USA", "Mexico"],
    description: "Century plant blooms only once after decades of growth, producing a massive flower spike loaded with nectar. A desert hummingbird magnet.",
    attractsSpecies: ["Blue-throated Mountain-gem", "Black-chinned Hummingbird", "Costa's Hummingbird"],
    tags: ["drought-tolerant", "desert-garden", "once-in-a-lifetime-bloom", "architectural"],
  },
  {
    name: "Ocotillo",
    scientificName: "Fouquieria splendens",
    type: "shrub",
    usdaZones: "8–11",
    bloomMonths: [3, 4, 5],
    color: "Red",
    colorHex: "#c0392b",
    pollinatorScore: 91,
    height: "8–20 ft",
    sunRequirement: "full-sun",
    waterNeeds: "low",
    nativeRegions: ["Chihuahuan Desert", "Sonoran Desert"],
    description: "Iconic Sonoran Desert plant with brilliant red flower clusters at branch tips. Synchronizes blooming with hummingbird spring migration.",
    attractsSpecies: ["Costa's Hummingbird", "Black-chinned Hummingbird", "Rufous Hummingbird"],
    tags: ["native", "desert-garden", "drought-tolerant", "spring-bloomer"],
  },
  {
    name: "Trumpet Honeysuckle",
    scientificName: "Lonicera x brownii",
    type: "vine",
    usdaZones: "4–9",
    bloomMonths: [5, 6, 7, 8],
    color: "Orange-Red",
    colorHex: "#ff6f00",
    pollinatorScore: 89,
    height: "6–12 ft",
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    nativeRegions: ["Garden hybrid"],
    description: "Showy hybrid honeysuckle with large tubular orange-red flowers. Long blooming season. Excellent for trellises and fences.",
    attractsSpecies: ["Ruby-throated Hummingbird", "Rufous Hummingbird"],
    tags: ["long-bloomer", "easy-care", "trellis"],
  },
];

export const usdaZones = [
  { zone: "1", temp: "Below -60°F", region: "Interior Alaska" },
  { zone: "2", temp: "-50 to -40°F", region: "Northern Alaska, Canada" },
  { zone: "3", temp: "-40 to -30°F", region: "Northern Plains, Canada" },
  { zone: "4", temp: "-30 to -20°F", region: "Northern Midwest, New England" },
  { zone: "5", temp: "-20 to -10°F", region: "Northeast, Midwest" },
  { zone: "6", temp: "-10 to 0°F", region: "Mid-Atlantic, Midwest" },
  { zone: "7", temp: "0 to 10°F", region: "Southeast, Pacific Northwest" },
  { zone: "8", temp: "10 to 20°F", region: "South, Pacific Coast" },
  { zone: "9", temp: "20 to 30°F", region: "Deep South, California" },
  { zone: "10", temp: "30 to 40°F", region: "Southern Florida, Southern California" },
  { zone: "11", temp: "40 to 50°F", region: "Hawaii, Puerto Rico" },
];

export const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
