export interface Species {
  slug: string;
  commonName: string;
  scientificName: string;
  family: string;
  length: string;
  weight: string;
  wingspan: string;
  lifespan: string;
  conservationStatus: "Least Concern" | "Near Threatened" | "Vulnerable" | "Endangered" | "Critically Endangered";
  conservationCode: "LC" | "NT" | "VU" | "EN" | "CR";
  range: string[];
  states: string[];
  habitat: string[];
  diet: string;
  nestingMonths: string;
  migrationMonths: { north: string; south: string };
  colors: { primary: string; secondary: string; throat?: string };
  colorTags: string[];
  description: string;
  facts: string[];
  flowers: string[];
  funFact: string;
  imageUrl: string;
  mapCenter: [number, number];
  mapZoom: number;
}

export const species: Species[] = [
  {
    slug: "ruby-throated-hummingbird",
    commonName: "Ruby-throated Hummingbird",
    scientificName: "Archilochus colubris",
    family: "Trochilidae",
    length: "7–9 cm (2.8–3.5 in)",
    weight: "2–6 g (0.071–0.212 oz)",
    wingspan: "8–11 cm (3.1–4.3 in)",
    lifespan: "3–5 years (up to 9 in wild)",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Eastern North America", "Central America"],
    states: ["Alabama","Arkansas","Connecticut","Delaware","Florida","Georgia","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Nebraska","New Hampshire","New Jersey","New York","North Carolina","Ohio","Oklahoma","Pennsylvania","Rhode Island","South Carolina","Tennessee","Texas","Vermont","Virginia","West Virginia","Wisconsin"],
    habitat: ["Deciduous forests", "Forest edges", "Gardens", "Meadows", "Parks"],
    diet: "Nectar, small insects, spiders",
    nestingMonths: "April–August",
    migrationMonths: { north: "March–May", south: "July–October" },
    colors: { primary: "#2d7d46", secondary: "#a0c878", throat: "#c1121f" },
    colorTags: ["green", "red", "ruby-throat", "iridescent"],
    description: "The Ruby-throated Hummingbird is the most common and widespread hummingbird in eastern North America. Males are distinguished by their brilliant iridescent ruby-red throat patch. These tiny birds make an incredible non-stop migration across the Gulf of Mexico — up to 500 miles in a single flight.",
    facts: [
      "Can beat their wings 53 times per second",
      "Only hummingbird that breeds in eastern North America",
      "Migrates non-stop across the Gulf of Mexico — about 500 miles",
      "Heart beats 1,200 times per minute during flight",
      "Brain is 4.2% of body weight — proportionally one of the largest in birds",
      "Can fly backwards and hover in place",
      "Body temperature drops to 54°F during torpor to conserve energy",
      "Males arrive at breeding grounds 1–2 weeks before females",
    ],
    flowers: ["Trumpet vine", "Bee balm", "Cardinal flower", "Coral honeysuckle", "Salvia", "Columbine", "Impatiens"],
    funFact: "A ruby-throated hummingbird must consume roughly half its body weight in sugar each day to fuel its hyperactive lifestyle!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Ruby-throated_hummingbird_frequents_red_buckeye.jpg/640px-Ruby-throated_hummingbird_frequents_red_buckeye.jpg",
    mapCenter: [38, -80],
    mapZoom: 4,
  },
  {
    slug: "anna-hummingbird",
    commonName: "Anna's Hummingbird",
    scientificName: "Calypte anna",
    family: "Trochilidae",
    length: "9.9–10.9 cm (3.9–4.3 in)",
    weight: "3.4–6 g (0.12–0.21 oz)",
    wingspan: "12 cm (4.7 in)",
    lifespan: "Up to 8 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Pacific Coast of North America"],
    states: ["California", "Oregon", "Washington", "Arizona", "Nevada"],
    habitat: ["Chaparral", "Oak woodlands", "Gardens", "Suburban areas", "Coastal scrub"],
    diet: "Nectar, insects, sap",
    nestingMonths: "December–June",
    migrationMonths: { north: "Year-round resident", south: "Year-round resident" },
    colors: { primary: "#4a7c59", secondary: "#8fbc8f", throat: "#c850c0" },
    colorTags: ["green", "pink", "magenta", "iridescent"],
    description: "Anna's Hummingbird is a year-round resident of the Pacific Coast, making it the only hummingbird that doesn't migrate. Males display a brilliant rose-pink gorget that extends over the crown. They are known for their complex, buzzy songs — unusual among hummingbirds.",
    facts: [
      "One of the only hummingbirds that sings a complex song",
      "Year-round resident — doesn't migrate",
      "Nests as early as December in California",
      "Males dive at 385 body-lengths per second during display — one of the fastest animals relative to body size",
      "Can enter torpor during cold nights to conserve energy",
      "Population has greatly expanded northward since the 1930s",
    ],
    flowers: ["Fuchsia", "Salvia", "Penstemon", "Eucalyptus", "Aloe", "Currant"],
    funFact: "During courtship dives, Anna's Hummingbirds experience forces of up to 10 g — more than fighter jet pilots typically experience!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Anna%27s_Hummingbird%2C_Washington_State.jpg/640px-Anna%27s_Hummingbird%2C_Washington_State.jpg",
    mapCenter: [37, -120],
    mapZoom: 5,
  },
  {
    slug: "rufous-hummingbird",
    commonName: "Rufous Hummingbird",
    scientificName: "Selasphorus rufus",
    family: "Trochilidae",
    length: "7–9 cm (2.8–3.5 in)",
    weight: "2.7–4.5 g (0.095–0.159 oz)",
    wingspan: "11 cm (4.3 in)",
    lifespan: "Up to 8 years",
    conservationStatus: "Near Threatened",
    conservationCode: "NT",
    range: ["Western North America", "Mexico"],
    states: ["Alaska", "Washington", "Oregon", "California", "Idaho", "Montana", "Wyoming"],
    habitat: ["Mountain meadows", "Forest edges", "Shrublands", "Coastal areas"],
    diet: "Nectar, insects",
    nestingMonths: "April–July",
    migrationMonths: { north: "March–May", south: "July–October" },
    colors: { primary: "#c17f3b", secondary: "#e8a85a", throat: "#ff6b35" },
    colorTags: ["rufous", "orange", "rust", "brown"],
    description: "The Rufous Hummingbird undertakes one of the longest migrations of any bird relative to body size — traveling up to 3,900 miles from Mexico to Alaska. Males are distinctive with their bright orange-red (rufous) plumage.",
    facts: [
      "Undertakes the longest migration of any hummingbird — up to 3,900 miles",
      "One of the most aggressive hummingbirds; will chase away much larger birds",
      "Can remember the location of thousands of flowers",
      "Among the northernmost breeding hummingbirds, nesting as far as southeastern Alaska",
      "Population has declined ~60% since 1970",
    ],
    flowers: ["Columbine", "Paintbrush", "Penstemon", "Salvia", "Monkeyflower", "Red clover"],
    funFact: "Pound for pound, the Rufous Hummingbird flies farther than any other bird on Earth relative to its body size!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Rufous_Hummingbird%2C_Victoria%2C_BC.jpg/640px-Rufous_Hummingbird%2C_Victoria%2C_BC.jpg",
    mapCenter: [52, -120],
    mapZoom: 4,
  },
  {
    slug: "black-chinned-hummingbird",
    commonName: "Black-chinned Hummingbird",
    scientificName: "Archilochus alexandri",
    family: "Trochilidae",
    length: "8.25 cm (3.25 in)",
    weight: "2.3–4.9 g",
    wingspan: "11 cm (4.3 in)",
    lifespan: "Up to 10 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Western North America", "Mexico"],
    states: ["Texas", "New Mexico", "Arizona", "Colorado", "Utah", "Nevada", "California", "Oregon", "Washington", "Idaho"],
    habitat: ["Mountain forests", "Semi-arid valleys", "Riparian areas", "Gardens"],
    diet: "Nectar, insects, spiders",
    nestingMonths: "April–August",
    migrationMonths: { north: "March–May", south: "August–October" },
    colors: { primary: "#3a5a40", secondary: "#95b894", throat: "#2c2c54" },
    colorTags: ["green", "black", "purple", "iridescent"],
    description: "The Black-chinned Hummingbird is one of the most adaptable hummingbirds in the West, found everywhere from desert to mountain forest. Males have a distinctive black chin with a purple-violet lower band that's only visible in good light.",
    facts: [
      "Their throat appears all black in most lighting — the purple band is only visible at the right angle",
      "Can drop their metabolic rate dramatically during cold nights",
      "One of the most widespread western hummingbirds",
      "Females alone build the nest and raise young",
    ],
    flowers: ["Desert willow", "Agave", "Salvia", "Penstemon", "Sage", "Ocotillo"],
    funFact: "The Black-chinned Hummingbird can rotate its wings in a full circle — the only bird known to do so!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Black-chinned_Hummingbird.jpg/640px-Black-chinned_Hummingbird.jpg",
    mapCenter: [35, -108],
    mapZoom: 5,
  },
  {
    slug: "blue-throated-mountain-gem",
    commonName: "Blue-throated Mountain-gem",
    scientificName: "Lampornis clemenciae",
    family: "Trochilidae",
    length: "11.5–12.5 cm (4.5–5 in)",
    weight: "6–10 g",
    wingspan: "18 cm (7.1 in)",
    lifespan: "Up to 12 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Southwestern USA", "Mexico"],
    states: ["Arizona", "New Mexico", "Texas"],
    habitat: ["Mountain canyons", "Pine-oak forests", "Riparian corridors"],
    diet: "Nectar, insects",
    nestingMonths: "May–August",
    migrationMonths: { north: "April–May", south: "September–October" },
    colors: { primary: "#2f6690", secondary: "#6ea8c8", throat: "#0055a4" },
    colorTags: ["blue", "green", "gray", "iridescent"],
    description: "The largest hummingbird regularly found in the United States, the Blue-throated Mountain-gem dazzles with its brilliant sky-blue gorget. Found in high mountain canyons of southeastern Arizona, New Mexico, and the Chisos Mountains of Texas.",
    facts: [
      "Largest hummingbird regularly occurring in the US",
      "Males have a distinctive loud call — 'seep seep'",
      "Blue gorget shines brilliantly only in direct light",
      "Often nests on ledges behind waterfalls",
      "Will aggressively defend feeding territories",
      "One nest has been used across multiple years",
    ],
    flowers: ["Salvia", "Agave", "Lobelia", "Penstemon", "Monarda"],
    funFact: "Blue-throated Mountain-gems are so loud for a hummingbird that their calls can be heard from over 100 feet away!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Blue-throated_Hummingbird.jpg/640px-Blue-throated_Hummingbird.jpg",
    mapCenter: [31.5, -110],
    mapZoom: 6,
  },
  {
    slug: "broad-tailed-hummingbird",
    commonName: "Broad-tailed Hummingbird",
    scientificName: "Selasphorus platycercus",
    family: "Trochilidae",
    length: "9–10.2 cm (3.5–4 in)",
    weight: "2.8–4.5 g",
    wingspan: "13.3 cm (5.2 in)",
    lifespan: "Up to 12 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Western North America", "Mexico", "Guatemala"],
    states: ["Colorado", "Utah", "Arizona", "New Mexico", "Nevada", "Wyoming", "Idaho", "Montana"],
    habitat: ["Mountain meadows", "Open pine forests", "Sagebrush plains"],
    diet: "Nectar, insects",
    nestingMonths: "May–August",
    migrationMonths: { north: "April–May", south: "August–October" },
    colors: { primary: "#3a7d44", secondary: "#a0c878", throat: "#e63946" },
    colorTags: ["green", "rose", "red", "iridescent"],
    description: "The Broad-tailed Hummingbird is a high-altitude specialist, breeding in mountain meadows and pine forests up to 10,500 feet. Males produce a distinctive wing trill that's been compared to a cricket's chirp.",
    facts: [
      "Males produce a cricket-like wing trill in flight",
      "Physiologically adapted to cold — can endure near-freezing temperatures",
      "Females often return to the same nesting site each year",
      "Among the highest-altitude breeding hummingbirds in North America",
      "Can enter torpor at night, dropping heart rate from 1,260 to 50 beats per minute",
    ],
    flowers: ["Indian paintbrush", "Scarlet gilia", "Penstemon", "Sage", "Columbine"],
    funFact: "Broad-tailed Hummingbirds have special blood hemoglobin that binds oxygen more efficiently — a high-altitude adaptation!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Broad-tailed_Hummingbird.jpg/640px-Broad-tailed_Hummingbird.jpg",
    mapCenter: [39, -105],
    mapZoom: 5,
  },
  {
    slug: "calliope-hummingbird",
    commonName: "Calliope Hummingbird",
    scientificName: "Selasphorus calliope",
    family: "Trochilidae",
    length: "7–10 cm (2.8–3.9 in)",
    weight: "2.3–3.4 g",
    wingspan: "10.5 cm (4.1 in)",
    lifespan: "Up to 8 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Western North America", "Mexico"],
    states: ["Montana", "Idaho", "Wyoming", "Colorado", "Utah", "Nevada", "Oregon", "Washington", "California"],
    habitat: ["Mountain meadows", "Brushy areas", "Open coniferous forests"],
    diet: "Nectar, insects",
    nestingMonths: "May–July",
    migrationMonths: { north: "April–May", south: "July–September" },
    colors: { primary: "#5a7a5c", secondary: "#b5d5b5", throat: "#c678dd" },
    colorTags: ["green", "purple", "magenta", "streaked"],
    description: "The Calliope Hummingbird is the smallest breeding bird in North America, yet it migrates more than 5,000 miles round-trip. Males sport a distinctive wine-red gorget with individual feathers that can flare out like whiskers.",
    facts: [
      "Smallest breeding bird in North America",
      "Migrates more than 5,000 miles round-trip",
      "Males have distinctive gorget feathers that flare like star-burst rays",
      "Despite tiny size, can displace much larger birds from feeders",
      "Often nests in old pine cones for camouflage",
    ],
    flowers: ["Paintbrush", "Glacier lily", "Penstemon", "Currant", "Willow"],
    funFact: "The Calliope Hummingbird weighs less than a ping-pong ball yet crosses the Rocky Mountains twice each year!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Calliope_Hummingbird.jpg/640px-Calliope_Hummingbird.jpg",
    mapCenter: [46, -115],
    mapZoom: 5,
  },
  {
    slug: "allens-hummingbird",
    commonName: "Allen's Hummingbird",
    scientificName: "Selasphorus sasin",
    family: "Trochilidae",
    length: "7.5–9.0 cm (3.0–3.5 in)",
    weight: "2–4 g",
    wingspan: "11 cm (4.3 in)",
    lifespan: "Up to 6 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["California Coast", "Baja California", "Mexico (wintering)"],
    states: ["California", "Oregon"],
    habitat: ["Coastal scrub", "Chaparral", "Gardens", "Forest edges"],
    diet: "Nectar, insects",
    nestingMonths: "February–July",
    migrationMonths: { north: "January–March", south: "June–August" },
    colors: { primary: "#b5601f", secondary: "#e8a85a", throat: "#ff4500" },
    colorTags: ["rufous", "orange", "green", "iridescent"],
    description: "Nearly identical to the Rufous Hummingbird, Allen's Hummingbird breeds almost exclusively along a narrow strip of coastal California and Oregon. A subspecies in Southern California is non-migratory, while the northern population makes one of the earliest spring migrations.",
    facts: [
      "Very similar to Rufous — best distinguished by tail feathers",
      "Among the earliest spring migrants, arriving in January",
      "Coastal California subspecies is non-migratory",
      "Historically one of the first hummingbird species recorded",
    ],
    flowers: ["Fuchsia", "Salvia", "Monkeyflower", "Currant", "Eucalyptus"],
    funFact: "Allen's Hummingbird is one of the only birds that remains a full-time resident of coastal Southern California — living its entire life within a few square miles!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Allen%27s_Hummingbird.jpg/640px-Allen%27s_Hummingbird.jpg",
    mapCenter: [37, -122],
    mapZoom: 6,
  },
  {
    slug: "costa-hummingbird",
    commonName: "Costa's Hummingbird",
    scientificName: "Calypte costae",
    family: "Trochilidae",
    length: "7.6–8.8 cm (3.0–3.5 in)",
    weight: "2–3 g",
    wingspan: "11 cm (4.3 in)",
    lifespan: "Up to 6 years",
    conservationStatus: "Least Concern",
    conservationCode: "LC",
    range: ["Mojave Desert", "Sonoran Desert", "Baja California"],
    states: ["California", "Arizona", "Nevada", "Utah"],
    habitat: ["Desert scrub", "Chaparral", "Desert washes", "Dry open areas"],
    diet: "Nectar, insects",
    nestingMonths: "February–June",
    migrationMonths: { north: "February–March", south: "May–July" },
    colors: { primary: "#2d7a3e", secondary: "#95c878", throat: "#7b2d8b" },
    colorTags: ["green", "purple", "violet", "iridescent"],
    description: "The Costa's Hummingbird is a desert specialist, perfectly adapted to the dry scrublands of the American Southwest. Males have a spectacular violet-purple gorget with elongated side feathers that flare into a dramatic 'mustache.'",
    facts: [
      "Desert specialist that breeds earlier than most NA hummingbirds",
      "Can survive extreme heat through behavioral adaptations",
      "Males have dramatic flaring gorget feathers — one of the most spectacular displays",
      "Often sings from exposed perches — unusual for hummingbirds",
      "Nests are often built in the shade to prevent overheating",
    ],
    flowers: ["Ocotillo", "Desert lavender", "Chuparosa", "Fairy duster", "Penstemon"],
    funFact: "Costa's Hummingbirds can raise their body temperature during the hottest part of the day and pant like dogs to stay cool!",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Costa%27s_Hummingbird.jpg/640px-Costa%27s_Hummingbird.jpg",
    mapCenter: [34, -116],
    mapZoom: 6,
  },
];

export function getSpeciesBySlug(slug: string): Species | undefined {
  return species.find((s) => s.slug === slug);
}

export function getSpeciesByState(state: string): Species[] {
  return species.filter((s) => s.states.some(st => st.toLowerCase() === state.toLowerCase()));
}

export function getSpeciesByColor(color: string): Species[] {
  return species.filter((s) => s.colorTags.some(c => c.toLowerCase().includes(color.toLowerCase())));
}
